apiVersion: v1
kind: PersistentVolume
metadata:
 name: pvvol-jx03
 labels: 
    volume-type: nfs
    pv-name: pvvol-jx03
spec:
 capacity:
  storage: 35Gi
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 nfs:
   path: /exports/jx/03
   server: nfs.olsclab.net
   readOnly: false
