apiVersion: v1
kind: PersistentVolume
metadata:
 name: pvvol-jx02
 labels: 
    volume-type: nfs
    pv-name: pvvol-jx02
spec:
 capacity:
  storage: 35Gi
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 nfs:
   path: /exports/jx/02
   server: nfs.olsclab.net
   readOnly: false
